---

- name: Install Dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    # Required
    - build-essential
    - libssl-dev
    - git
    # Recommended (extra formats and performance)
    - yasm
    - libgmp-dev
    - libpcap-dev
    - pkg-config
    - libbz2-dev
    # MPI support
    - libopenmpi-dev
    - openmpi-bin

- name: Clone repository
  git:
    repo: "{{ johntheripper_repo }}"
    dest: "{{ johntheripper_dest }}"
    version: "{{ johntheripper_version }}"
    update: no
  register: gitclone

- name: Build source
  shell: ./configure --enable-mpi && make -sj4
  args:
    chdir: "{{ johntheripper_dest }}/src"
  notify: Test build
  when: gitclone.changed

- name: Set directory permissions
  file:
    path: "{{ johntheripper_dest }}"
    state: directory
    owner: "{{ johntheripper_owner }}"
    group: "{{ johntheripper_owner }}"

- name: Test JtR with MPI
  shell: "su mpiuser -c 'mpiexec -np 1 --host {{ item }} {{ johntheripper_dest }}/run/john --test=0'"
  with_items: "{{ groups['slaves'] }}"
  tags:
    - jtr_mpi_test
